spring:
  application:
    name: CIS-MSA-GATEWAY
  cloud:
    gateway:
      routes:
        - id : path_route
          uri : http://localhost:8180
          predicates:
            - Path=/api/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/fallback
security:
  oauth2:
    client:
      client-id: auth_id
      client-secret: auth_secret
    resource:
      jwt:
        key-value: jwt_secret_key
