spring:
  application:
    name: CIS-MSA-GATEWAY
  cloud:
    gateway:
      routes:
        - id: path_auth
          uri: http://localhost:8095
          predicates:
            - Path=/oauth/**
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/fallback
        - id : path_order
          uri : http://localhost:8180
          predicates:
            - Path=/api/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/fallback
security:
  oauth2:
    resource:
      jwt:
        key-value: jwt_secret_key
